# Generated by nixos-infect — Oracle Cloud A1.Flex (aarch64)
# UUIDs and modules from actual hardware detection
{ lib, modulesPath, ... }:
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "xen_blkfront"
  ];
  boot.initrd.kernelModules = [ "nvme" ];

  fileSystems."/" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };
  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/AC23-31FF";
    fsType = "vfat";
  };

  swapDevices = [ ]; # Using zram

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
