# Pelican Panel + Wings — game server management
# Panel installed manually at /var/www/pelican (Laravel + SQLite)
# Wings is a Go binary managing Docker containers
{
  config,
  pkgs,
  lib,
  ...
}:

let
  php = pkgs.php83.withExtensions (
    { enabled, all }:
    enabled
    ++ (with all; [
      gd
      mbstring
      bcmath
      xml
      curl
      zip
      intl
      sqlite3
      pdo_sqlite
      tokenizer
      fileinfo
    ])
  );
  panelDir = "/var/www/pelican";
  casaosContainerIp = "10.200.0.166";
in
{
  # PHP-FPM pool for Pelican
  services.phpfpm.pools.pelican = {
    user = "pelican";
    group = "pelican";
    phpPackage = php;
    settings = {
      "listen.owner" = config.services.caddy.user;
      "listen.group" = config.services.caddy.group;
      "pm" = "dynamic";
      "pm.max_children" = 4;
      "pm.start_servers" = 2;
      "pm.min_spare_servers" = 1;
      "pm.max_spare_servers" = 3;
    };
    phpEnv = {
      APP_ENV = "production";
    };
  };

  # Caddy — reverse proxy for all services on port 80
  services.caddy = {
    enable = true;
    virtualHosts = {
      # Pelican Panel — default (IP público + pelican.local)
      ":80" = {
        extraConfig = ''
          root * ${panelDir}/public
          php_fastcgi unix${config.services.phpfpm.pools.pelican.socket}
          file_server
        '';
      };
      # CasaOS — via hostname
      "http://casaos.local" = {
        extraConfig = ''
          reverse_proxy ${casaosContainerIp}:80
        '';
      };
    };
  };

  # Pelican queue worker (background jobs)
  systemd.services.pelican-queue = {
    description = "Pelican Queue Worker";
    after = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "simple";
      User = "pelican";
      Group = "pelican";
      WorkingDirectory = panelDir;
      ExecStart = "${php}/bin/php artisan queue:work --queue=high,standard,low --sleep=3 --tries=3";
      Restart = "on-failure";
      RestartSec = 5;
    };
  };

  # Pelican schedule (cron)
  systemd.services.pelican-schedule = {
    description = "Pelican Scheduler";
    after = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      User = "pelican";
      Group = "pelican";
      WorkingDirectory = panelDir;
      ExecStart = "${php}/bin/php artisan schedule:run";
    };
  };

  systemd.timers.pelican-schedule = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "*:0/1"; # every minute
      Persistent = true;
    };
  };

  # Wings daemon — manages game server Docker containers
  # Binary installed manually at /etc/pelican/wings
  # Config generated by Panel at /etc/pelican/config.yml
  systemd.services.wings = {
    description = "Pelican Wings Daemon";
    after = [ "docker.service" ];
    requires = [ "docker.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "/etc/pelican/wings";
      Restart = "on-failure";
      RestartSec = 5;
      LimitNOFILE = 4096;
      WorkingDirectory = "/etc/pelican";
    };
  };

  # Pelican system user
  users.users.pelican = {
    isSystemUser = true;
    group = "pelican";
    home = panelDir;
  };
  users.groups.pelican = { };

  # Ensure panel directory has correct ownership
  systemd.tmpfiles.rules = [
    "d ${panelDir}/storage 0755 pelican pelican -"
    "d ${panelDir}/storage/app 0755 pelican pelican -"
    "d ${panelDir}/storage/framework 0755 pelican pelican -"
    "d ${panelDir}/storage/framework/cache 0755 pelican pelican -"
    "d ${panelDir}/storage/framework/sessions 0755 pelican pelican -"
    "d ${panelDir}/storage/framework/views 0755 pelican pelican -"
    "d ${panelDir}/storage/logs 0755 pelican pelican -"
    "d ${panelDir}/bootstrap/cache 0755 pelican pelican -"
  ];

  # PHP + Composer in system packages for manual maintenance
  environment.systemPackages = [
    php
    pkgs.php83Packages.composer
  ];
}
