# Pelican Panel + Wings — game server management
#
# NixOS provides: Caddy, PHP-FPM, systemd services (queue worker, scheduler, wings)
# Panel code is installed MANUALLY (Laravel app, not nixified).
#
# === First-time setup ===
#
# 1. Install panel:
#    mkdir -p /var/www/pelican && cd /var/www/pelican
#    curl -L https://github.com/pelican-dev/panel/releases/latest/download/panel.tar.gz | tar -xzv
#    COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader
#
# 2. Setup database and app key:
#    php artisan key:generate --force
#    php artisan migrate --seed --force
#
# 3. Create admin user:
#    php artisan p:user:make --email=EMAIL --username=USER --password=PASS --admin=1 --no-interaction
#
# 4. Fix ownership:
#    chown -R pelican:pelican /var/www/pelican
#    chmod -R 755 /var/www/pelican/storage /var/www/pelican/bootstrap/cache
#
# 5. Configure Wings (after creating a Node in the Panel UI):
#    curl -sfL https://github.com/pelican-dev/wings/releases/download/v1.0.0-beta24/wings_linux_arm64 -o /etc/pelican/wings
#    chmod +x /etc/pelican/wings
#    /etc/pelican/wings configure --panel-url http://10.100.0.1 --token TOKEN --node 1 --allow-insecure --config /var/lib/wings/config.yml
#    systemctl restart wings
#
# === Updating ===
#
# cd /var/www/pelican
# curl -L https://github.com/pelican-dev/panel/releases/latest/download/panel.tar.gz | tar -xzv
# COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader
# php artisan migrate --force
# chown -R pelican:pelican /var/www/pelican
{
  config,
  pkgs,
  lib,
  ...
}:

let
  php = pkgs.php83.withExtensions (
    { enabled, all }:
    enabled
    ++ (with all; [
      gd
      mbstring
      bcmath
      xml
      curl
      zip
      intl
      sqlite3
      pdo_sqlite
      tokenizer
      fileinfo
    ])
  );
  panelDir = "/var/www/pelican";
in
{
  # PHP-FPM pool for Pelican
  services.phpfpm.pools.pelican = {
    user = "pelican";
    group = "pelican";
    phpPackage = php;
    settings = {
      "listen.owner" = config.services.caddy.user;
      "listen.group" = config.services.caddy.group;
      "pm" = "dynamic";
      "pm.max_children" = 4;
      "pm.start_servers" = 2;
      "pm.min_spare_servers" = 1;
      "pm.max_spare_servers" = 3;
    };
    phpEnv = {
      APP_ENV = "production";
    };
  };

  # Caddy virtualhost for Pelican Panel (default, IP público + pelican.local)
  services.caddy.enable = true;
  services.caddy.virtualHosts.":80" = {
    extraConfig = ''
      root * ${panelDir}/public
      php_fastcgi unix${config.services.phpfpm.pools.pelican.socket}
      file_server
    '';
  };

  # Pelican queue worker (background jobs)
  systemd.services.pelican-queue = {
    description = "Pelican Queue Worker";
    after = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "simple";
      User = "pelican";
      Group = "pelican";
      WorkingDirectory = panelDir;
      ExecStart = "${php}/bin/php artisan queue:work --queue=high,standard,low --sleep=3 --tries=3";
      Restart = "on-failure";
      RestartSec = 5;
    };
  };

  # Pelican schedule (cron)
  systemd.services.pelican-schedule = {
    description = "Pelican Scheduler";
    after = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      User = "pelican";
      Group = "pelican";
      WorkingDirectory = panelDir;
      ExecStart = "${php}/bin/php artisan schedule:run";
    };
  };

  systemd.timers.pelican-schedule = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "*:0/1"; # every minute
      Persistent = true;
    };
  };

  # Wings daemon — manages game server Docker containers
  # Binary installed manually at /etc/pelican/wings
  # Config generated by Panel at /etc/pelican/config.yml
  systemd.services.wings = {
    description = "Pelican Wings Daemon";
    after = [ "docker.service" ];
    requires = [ "docker.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "/etc/pelican/wings --config /var/lib/wings/config.yml";
      Restart = "on-failure";
      RestartSec = 5;
      LimitNOFILE = 4096;
      WorkingDirectory = "/var/lib/wings";
    };
  };

  # Pelican system user
  users.users.pelican = {
    isSystemUser = true;
    group = "pelican";
    home = panelDir;
  };
  users.groups.pelican = { };

  # Ensure panel directory has correct ownership
  systemd.tmpfiles.rules = [
    "d ${panelDir}/storage 0755 pelican pelican -"
    "d ${panelDir}/storage/app 0755 pelican pelican -"
    "d ${panelDir}/storage/framework 0755 pelican pelican -"
    "d ${panelDir}/storage/framework/cache 0755 pelican pelican -"
    "d ${panelDir}/storage/framework/sessions 0755 pelican pelican -"
    "d ${panelDir}/storage/framework/views 0755 pelican pelican -"
    "d ${panelDir}/storage/logs 0755 pelican pelican -"
    "d ${panelDir}/bootstrap/cache 0755 pelican pelican -"
  ];

  # PHP + Composer in system packages for manual maintenance
  environment.systemPackages = [
    php
    pkgs.php83Packages.composer
  ];
}
